# This file includes the configuration used to validate the chart with a dry-run installation.

exposeDomains:
  example:
    hostname: example.com
  example2:
    hostname: www.example.com
    ssl:
      enabled: true
      issuer: letsencrypt-staging

domainPrefixes: ['en', 'fi']

autoscaling:
  enabled: true

varnish:
  enabled: true

memcached:
  enabled: true

redis:
  enabled: true
  auth:
    password: foo

elasticsearch:
  enabled: true

mailhog:
  enabled: true

backup:
  enabled: true

mounts:
  private-files:
    enabled: true

cluster:
  type: ""
