

domain: downscaler.silta.wdr.io

ssl:
  enabled: true
  issuer: letsencrypt

# A cron schedule to determine when applications will be downscaled.
schedule: "0 4,18 * * *"

image: wunderio/silta-downscaler
tag: "v0.1.2"

resources:
  requests:
    cpu: 10m
    memory: 50Mi

# How long should releases be kept by default.
defaultMinAge: 1d

# How long should releases with matching names be kept. The last matching rule takes effect.
releaseMinAge:
  "^production": 10y
  "^(master|stage|staging)": 1w
  "^dependabot": 1h
