apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-drupal
  labels:
    app: drupal
    release: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app: drupal
    release: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-drupal
  labels:
    app: drupal
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: drupal
      release: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: drupal
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.nginx.image | quote }}
        name: nginx
        resources:
          requests:
            cpu: "50m"
        env:
        - name: NGINX_STATIC_CONTENT_OPEN_FILE_CACHE
          value: "off"
        - name: NGINX_ERROR_LOG_LEVEL
          value: debug
        - name: NGINX_BACKEND_HOST
          value: localhost
        - name: NGINX_SERVER_ROOT
          value: /var/www/html/web
        ports:
        - containerPort: 80
          name: drupal
        volumeMounts:
        - name: drupal-files-volume
          mountPath: /var/www/html/web/sites/default/files

      - image: "{{ .Values.drupal.image}}"
        name: drupal
        env:
        - name: DB_USER
          value: "{{ .Values.mariadb.db.user }}"
        - name: DB_NAME
          value: "{{ .Values.mariadb.db.name }}"
        - name: DB_HOST
          value: {{ .Release.Name }}-mariadb
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mariadb
              key: mariadb-password
        - name: HASH_SALT
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets-drupal
              key: hashsalt
        ports:
        - containerPort: 9000
          name: drupal
        volumeMounts:
        - name: drupal-files-volume
          mountPath: /var/www/html/web/sites/default/files
      imagePullSecrets:
      - name: gcr
      volumes:
      - name: drupal-files-volume
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-public-files
