{{- if and (eq .Values.cluster.type "gke") (.Values.backendConfig) }}
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: {{ .Release.Name }}-simple
  labels:
    {{- include "simple.release_labels" $ | nindent 4 }}
spec:
  {{- toYaml .Values.backendConfig | nindent 2 }}
{{- end }}
